akdb/src/auxi/auxiliary.c, akdb/src/srv/akdb_cli.py, akdb/src/srv/server.py, akdb/src/srv/server_functions.py, akdb/src/srv/sql_executor.py, akdb/src/srv/sql_executor_test.py, akdb/src/swig/relAlgebraTests.py, akdb/src/swig/selectionTests.py, akdb/src/swig/tablePropertiesTests.py, akdb/src/swig/test.py
Svi pronađeni ak, Ak su promijenjeni u AK. Većina promjena nalazi se u .py file-u.
=> #162 Promijenjeno ak u AK

akdb/src/sql/privileges.c
Fixed functions AK_user_add and AK_group_add so that the test doesn't fail if a user/group with the name already exists. Test 14 was confirmed to be fixed and working.
=> Fix test 46. issue #142

akdb/src/rel/expression_check.c
- implementacija relacijskih operatora IN, ANY i ALL
- implementirani za tipove VARCHAR, INT i FLOAT
- Implementirane sve vezije operatora ANY i ALL (>,<,>=,<=,=,!=,<>)
- napisani testovi za operatore IN, >ANY i <=ALL
=> Dodani operatori IN, ANY i ALL

akdb/src/sql/select.c
- AK_select now consists of multiple smaller functions
- comments improved
- BONUS - fixed a bug where test 42 was creating a huge table after each run.
=> #183 AK_select refactored and tests improved

akdb/src/sql/trigger.c, akdb/src/sql/trigger.h
Fixed: redolog issue, trigger editing, trigger fetching. 
Proper testing logic implemented.
=> #153 Trigger test (43.) fixed

akdb/.gitignore, akdb/Dockerfile, akdb/src/Makefile, akdb/src/srv/akdb_cli.py, akdb/src/srv/client.py, akdb/src/srv/server.py, akdb/src/srv/server_functions.py, akdb/src/srv/sql_executor.py, akdb/src/srv/sql_tokenizer.py, akdb/src/srv/sql_tokenizer_test.py, akdb/src/swig/allTests.py, akdb/src/swig/alter_table.py, akdb/src/swig/kalashnikovDB.i, akdb/src/swig/setup.py, akdb/src/swig/test.py, akdb/src/tools/comments.py
#177 
- /srv i /swig i comments.py helper migrirani u python3 uz pomoć [2to3](https://docs.python.org/3/library/2to3.html)
- make swig prerađen da generira python3 bindinge
- dodan python3 i njegov pip u dockerfile, python2 je ostavljen za slucaj da ga netko treba za nesto jos u buducnosti
- testovi rade kao i prije - ako su bili brejkani i dalje bacaju isti error, a ako su radili, sad i dalje rade (bilo je potrebno par fixeva)
=> Python2 to python3

akdb/src/file/table.c, akdb/src/file/table.h, akdb/src/main.c
Riješen sigsegv (char * se spremao u integer), dodani su komentari za funkcije i malo je počišćen kod.
=> riješen issue 171

akdb/src/auxi/dictionary.c, akdb/src/auxi/dictionary.h, akdb/src/auxi/iniparser.c, akdb/src/auxi/iniparser.h, akdb/src/main.c
Implemented 5 tests for dictionary.c implementation.
Implemented 9 tests for iniparser.c implementation.
TOTAL: 14 new tests
Tests are added in main.c and all are successful. Guidelines for Reporting Test Results were followed.
=> #184 - Implemented tests for dictionary.c and iniparser.c

.github/workflows/c-cpp.yml, .github/workflows/configure, akdb/src/doxygen.config
Additionally, follow these steps to get the necessary secret:
1. In the navbar click on the profile dropdown --> **Settings**
2. At the bottom of the left menu click **Developer Settings**
3. Click **Personal access token**
4. **Generate new token** with the following info
- note: AKDB_ACTION_KEY
- expiration: No expiration
- scopes: Select all of **repo**, **workflow**, **write:packages**, **delete:packages**
5. **Generate token**
6. Copy the token
7. Go to repo --> **Settings**
8. In the left menu click **Secrets** --> **Actions**
9. **New repository secret** with the following info
- name: AKDB_ACTION_KEY
- value: token copied in step 6
10. **Add secret**
=> #178 Added CI/CD pipeline with Github Actions

akdb/src/Makefile, akdb/src/main.c, akdb/src/rel/expression_check.c, akdb/src/tests.c, akdb/src/tests.h
Refaktorirati main.c na više manjih dijelova.
Done- napravio novi .h i .c file.
Napisati komentare gdje su potrebni, obrisati suvišne komentare.
Done- obrisao nebitne komentare, neke ostavio.
Preimenovati varijable tako da su u skladu s oslatim datotekama.
Done- promjenio imena varijabli gdje je imalo smisla, neke maknuo, neke ostavio.
Riješiti ponavljanje previše funkcija.
Done- tokom refaktorianja izmjenio neke sitnice i popravio sitne greške.
=> refactored main, did some other fixes too.

akdb/src/file/fileio.c, akdb/src/file/table.c, akdb/src/sql/cs/unique.c
Popravljena dva različita SIGSEGV slučaja kod testa
=> fix 2 SIGSEGVs

akdb/src/sql/drop.c, akdb/src/sql/drop.h, akdb/src/sql/function.c, akdb/src/sql/function.h
- refaktorirana funkcija DROP u više manjih funkcija
- popravljeni testovi
- nadograđen header file
- nadograđen function.c da može brisati funkcije bez argumenata
=> 150 - Popraviti DROP

akdb/src/srv/client.py
=> Promjena error poruka u client.py

akdb/src/sql/select.c, akdb/src/sql/view.c
Refaktoriran 201:AK_view_rename - optimizacija rename funkcije
Razlamanje funkcije 106:AK_select na manje funkcije s ciljem čitljivosti, usklađeno imenovanje varijabli, refaroktirane helper funkcije.
=> Refaktor view.c i select.c fileova

akdb/src/rel/selection.c
Dealocirana memorija prije izlaza. Popravljen ispis i dodan komentar. Maknute break naredbe i promijenjeni if uvjeti.
=> issue243_selection.c

akdb/src/file/blobs.c
- Upotrijebljena clang-format ekstenzija za formatiranje koda u blobs.c
- Prikladno izmijenjena funkcija u retku 93 za provjeru postojanja bloba i u njoj izbrisana nepotrebna varijabla
- Dodani potrebni komentari za dvije funkcije u redcima 240 i 263
=> Pull request za issue #229

akdb/src/auxi/mempro.c, akdb/src/sql/drop.c, akdb/src/sql/drop.h, akdb/src/sql/function.c, akdb/src/sql/function.h
24.5.2023.
Ispravljen i poboljšan kod radi lakšeg razumijevanja i održavanja.
Dodani i ispravljeni pojedini komentari.
Dodana funkcija “AK_get_function_details_by_obj_id”, ali nije u potpunosti implementirana.
**Test 38** se pokrene i uspješno završi.
6.6.2023.
Nakon što se test pokrene par puta i svaki put uspješno završi, prilikom jednog izvođenja javlja se slijedeća greška i test staje:
Greška se nalazi u mempro.c datoteci, u liniji 757 u funkciji “AK_debmod_fstack_push”. Vrijednost “fstack_size” je premašila vrijednost “AK_DEBMOD_STACKSIZE” i test se prekinuo. Assertion provjerava velicinu “fstack_size” i uspoređuje ju sa veličinom “AK_DEBMOD_STACKSIZE”. Ako uvjet nije ispunjen test prestaje.
Na lokaciji koja je navedena u greški u komentarima piše stack overflow. Stack je struktura …
=> Popraviti DROP #150

akdb/src/rel/aggregation.c, akdb/src/rel/aggregation.h, akdb/src/rel/selection.c, akdb/src/rel/selection.h, akdb/src/tests.c
Dodane GROUP BY i HAVING funkcije. Uz HAVING dodne funkcije AK_create_expr_node, AK_append_attribute, AK_free_expr_node. Uz to su dodani i implementirani testovi test_groupBy i test_having. Test group by uspješno prolazi dok test HAVING kao i kod određenih drugih testova ima problem s alokacijom memorije.
=> Mbogesic_having_groupby

akdb/src/html_files/customdoxygen.css, akdb/src/html_files/footer.html, akdb/src/html_files/header.html
Popravljena dokumantacija u html files - Pobrisan višak koda, uklonjeni nepotrebni komentari i ureden kod.
doc/ je prazan stoga ne postoje putanje za ispravljanje
=> fix html documentation

akdb/src/rel/nat_join.c
Test 27 radi ok, kompletna promjena AK_op_join, problem s dealokacijom
=> Test 27 radi, promjena testa AK_op_join (problem s dealokacijom)

akdb/src/rel/aggregation.c
Popunjeni prazni caseovi u switch petljama za različite operacije aggregacije, obrisan dugi komentar koji je postavljen radi citkosti, Nakon dodanog koda testovi se izvrsavaju i kao prije izmjena. Izmjene su napravljene inspiracijom na issue [#158](https://github.com/minovakovi/akdb/issues/158) kao pokušaj riješenje problema proširen je mehanizam brisanja odnosno dealocirana za svaki različiti task kako bi se test mogao provesti.
[obrisani komentar.txt](https://github.com/minovakovi/akdb/files/11713433/obrisani.komentar.txt)
=> Ažuriranje datoteke aggregation.c -> popunjeni caseovi za različite mehanizme aggregiranja

akdb/src/rel/aggregation.c
=> Revert "Ažuriranje datoteke aggregation.c -> popunjeni caseovi za različite mehanizme aggregiranja"

akdb/src/dm/dbman.c, akdb/src/file/table.c
=> Revert "fix: refactor ak_print_block function and fix memory leak and code fi…"

akdb/src/rel/nat_join.c
=> Revert "izmjena u datoteci nat_join.c"

akdb/src/auxi/constants.h, akdb/src/auxi/debug.c, akdb/src/auxi/dictionary.c, akdb/src/auxi/iniparser.c, akdb/src/rel/aggregation.c
=> popravak issue-a 174

akdb/src/rel/expression_check.c
Riješeni problemi navedeni u issue #238:
-  izdvojena evaluacija svih logičkih operatora u zasebne funkcije
- optimizirana check_arithmetic_statement funkcija na način da je kreiran enum za operatore a evaluacije po svakom od operatora su izdvojene u pomoćne funkcije
- test 38 se izvodi uspješno
- uočen nedovršen TODO dodavanja opisa za test funkciju, pa je opis dodan
=> Optimizacija koda - expression_check

akdb/src/auxi/constants.h, akdb/src/file/idx/bitmap.c, akdb/src/file/idx/bitmap.h, akdb/src/rel/nat_join.c, akdb/src/rel/theta_join.c, akdb/src/sql/privileges.c
dodane imenovane konstante na kraj constants.h koje su spremne za opću primjenu
=> dodavanje imenovanih konstanti u constants.h, primjena unutar datoteka

.gitignore, akdb/Makefile, akdb/README.md, akdb/docker-compose.yml, akdb/src/Makefile
Dodane jasne upute za runanje docker konteinera sa mountanjem lokalnih datoteka  i dodana mogucnost pokretanja preko  docker compose za bolju kontrolu sa jednom naredbom "make docker-compose".
=> Updated docker make install and run files

akdb/src/rel/intersect.c
Ispravljen i refaktoriran AK_intersect. Test_AK_intersect prolazi.
=> Ispravljen i refaktoriran intersect (issue #281)

akdb/src/dm/dbman.c, akdb/src/sql/privileges.c, akdb/src/sql/privileges.h
Added salting to the existing hash function and added a function that can change the password of a certain user (3VJ).
=> Added salt and password change function (Issue 305)

akdb/src/rel/aggregation.c
Bolja preglednosti i čitljivost
Popravljen izračun i spremanje vrijednosti za sum i count
Dodani komentari na bitnije dijelove koda
=> Refaktoriran AK_aggregate 

akdb/src/srv/modules/conditional_module.py, akdb/src/srv/modules/creating_structure_module.py, akdb/src/srv/modules/get_module.py, akdb/src/srv/sql_executor.py, akdb/src/srv/sql_tokenizer.py, akdb/src/srv/tests.py, akdb/src/swig/setup.py, akdb/src/tools/comments.py
Izmjenna iz py2 u py3, maknute deprecated funkcije i moduli, zamjenjene sa suvremenijima
=> Promjena py datoteka iz py2 u py3
